name: PSB
version: ${project.version}
main: org.b0b0bo.pathspeedboost.PathSpeedBoostPlugin
authors:
  - b0b0b0
  - 1050TI_top
  - OverwriteMC
description: Increases player speed by a configurable percentage when moving on a dirt path.
commands:
  psb:
    description: Main command for the PSB Plugin.
    usage: /<command> <subcommand>
    aliases: [pathspeedboost]
    permission: pathspeedboost.admin
    permission-message: You do not have permission to use this command.
permissions:
  pathspeedboost.admin:
    description: Allows the user to reload the PSB Plugin configuration and open the settings GUI.
    default: op

